app = "ahmedbot-cryp-auto"
primary_region = "iad"

[build]

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "http"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
